services:
  stats-server:
    build: statisticService/server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 40s

  ewm-service:
    build: mainService
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"


  stat-db:
    image: postgres:16.1
    container_name: stat-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stat
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
