services:
  stats-server:
    build: statisticService/server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ewm-service:
    build: mainService
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  stat-db:
    image: postgres:16.1
    container_name: stat-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=stat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stat -d stat"]
      timeout: 5s
      interval: 5s
      retries: 10

  main-db:  # ← ДОЛЖЕН БЫТЬ НА ТОМ ЖЕ УРОВНЕ, ЧТО И stat-db!
    image: postgres:16.1
    container_name: main-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U main -d main"]
      timeout: 5s
      interval: 5s
      retries: 10